// test/cli-sync.test.js
// E2E tests for `skilltags sync` — the core command that generates category files.

import { describe, test, expect, beforeEach, afterEach } from 'vitest';
import { createSandbox } from './helpers/sandbox.js';

describe('skilltags sync', () => {
  let sandbox;

  beforeEach(async () => { sandbox = await createSandbox(); });
  afterEach(async () => { await sandbox.cleanup(); });

  test('no config: prints guidance message and exits 0', async () => {
    const result = await sandbox.run(['sync']);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('No categories configured');
  });

  test('no config with --quiet: produces no output', async () => {
    const result = await sandbox.run(['sync', '--quiet']);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toBe('');
  });

  test('implicit sync (no subcommand) works the same', async () => {
    const result = await sandbox.run([]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('No categories configured');
  });

  describe('with config and skills', () => {
    beforeEach(async () => {
      await sandbox.seedSkills('home');
      await sandbox.seedConfig({
        version: '2.1.2',
        categories: {
          frontend: ['react-components'],
          database: ['postgres-optimization'],
        },
      });
    });

    test('generates st-*.md files in global commands dir', async () => {
      const result = await sandbox.run(['sync']);
      expect(result.exitCode).toBe(0);
      expect(result.stdout).toContain('Found');
      expect(result.stdout).toContain('skill');

      const frontend = await sandbox.readFile('.cursor/commands/st-frontend.md');
      expect(frontend).toContain('React Components');
      expect(frontend).toContain('react-components');

      const database = await sandbox.readFile('.cursor/commands/st-database.md');
      expect(database).toContain('Postgres Optimization');
    });

    test('generated files contain the header template', async () => {
      await sandbox.run(['sync']);
      const frontend = await sandbox.readFile('.cursor/commands/st-frontend.md');
      expect(frontend).toContain('# Skills: Frontend');
      expect(frontend).toContain('Auto-generated by skilltags');
      expect(frontend).toContain('CRITICAL REQUIREMENT');
    });

    test('--quiet suppresses output but still generates files', async () => {
      const result = await sandbox.run(['sync', '--quiet']);
      expect(result.exitCode).toBe(0);
      expect(result.stdout).toBe('');

      const frontend = await sandbox.readFile('.cursor/commands/st-frontend.md');
      expect(frontend).toContain('React Components');
    });

    test('stdout lists generated files with skill counts', async () => {
      const result = await sandbox.run(['sync']);
      expect(result.stdout).toMatch(/st-frontend\.md.*1 skill/);
      expect(result.stdout).toMatch(/st-database\.md.*1 skill/);
    });
  });

  describe('--local flag', () => {
    beforeEach(async () => {
      await sandbox.seedSkills('project', '.agents/skills');
      await sandbox.seedConfig({
        version: '2.1.2',
        categories: {
          frontend: ['react-components'],
        },
      }, 'project');
    });

    test('writes to project .cursor/commands/ instead of global', async () => {
      const result = await sandbox.run(['sync', '--local']);
      expect(result.exitCode).toBe(0);

      const frontend = await sandbox.readFile('.cursor/commands/st-frontend.md', 'project');
      expect(frontend).toContain('React Components');

      const globalExists = await sandbox.fileExists('.cursor/commands/st-frontend.md', 'home');
      expect(globalExists).toBe(false);
    });
  });

  test('empty category produces no output file', async () => {
    await sandbox.seedConfig({
      version: '2.1.2',
      categories: {
        frontend: [],
      },
    });

    await sandbox.run(['sync']);
    const exists = await sandbox.fileExists('.cursor/commands/st-frontend.md');
    expect(exists).toBe(false);
  });

  test('category with unmatched skill names still generates a file', async () => {
    await sandbox.seedSkills('home');
    await sandbox.seedConfig({
      version: '2.1.2',
      categories: {
        frontend: ['react-components', 'nonexistent-skill'],
      },
    });

    await sandbox.run(['sync']);
    const frontend = await sandbox.readFile('.cursor/commands/st-frontend.md');
    expect(frontend).toContain('React Components');
  });

  test('snapshot: generated frontend file content', async () => {
    await sandbox.seedSkills('home');
    await sandbox.seedConfig({
      version: '2.1.2',
      categories: {
        frontend: ['react-components'],
      },
    });

    await sandbox.run(['sync']);
    const frontend = await sandbox.readFile('.cursor/commands/st-frontend.md');
    expect(frontend).toMatchSnapshot();
  });
});
