// lib/writer.js
// Generate st-{category}.md command files from config and discovered skills.

'use strict';

const fs = require('fs');
const path = require('path');
const { VERSION } = require('./config');
const { toTitleCase } = require('./categories');

const HEADER_TEMPLATE = (title) => `# Skills: ${title}

<!-- Auto-generated by skilltags v${VERSION} — do not edit manually -->

Assess the following ${title} skills available in this workspace and apply any that are relevant to completing the user's request at the highest level of efficiency, quality, and completeness. When skills overlap in scope, assess the overlapping skills in greater detail and autonomously determine which is the best match for the project or the specific request — do not prompt the user to resolve overlaps.

CRITICAL REQUIREMENT: Before applying any skill, you MUST use the Read tool to read the full contents of the skill file at the provided path. Do not assume the skill's behavior from its title or description alone.

If operating in Plan Mode, explicitly include references to specific skills to use and (if applicable) subagents to utilize for efficient programming within the contents of the plan and the plan's TODOs.

Examples:
- "Use the \`responsive-design/SKILL.md\` to apply advanced clamp-based responsiveness to the new navigation bar."
- "Delegate to the \`frontend-designer\` subagent using \`ui-ux-pro-max/SKILL.md\` to build the polished component."
- "Utilize \`supabase-postgres-best-practices/SKILL.md\` when designing the database schema for the user profiles."

## ${title} Skills
`;

function generateCategoryFile(categoryName, skillNames, allSkills, commandsDir) {
  const title = toTitleCase(categoryName);
  const outPath = path.join(commandsDir, `st-${categoryName}.md`);

  const skillMap = new Map(allSkills.map(s => [s.name, s]));
  let skillsSection = '';

  for (const name of skillNames) {
    const skill = skillMap.get(name);
    if (!skill) continue;
    skillsSection += `\n### ${skill.title}\n\`${skill.path}\`\n\n${skill.description}\n`;
  }

  const content = HEADER_TEMPLATE(title) + skillsSection;
  fs.mkdirSync(commandsDir, { recursive: true });
  fs.writeFileSync(outPath, content, 'utf-8');

  return { path: outPath, count: skillNames.filter(n => skillMap.has(n)).length };
}

function generateAllCategoryFiles(config, allSkills, commandsDir) {
  const results = [];
  const categories = config.categories || {};

  for (const [catName, skillNames] of Object.entries(categories)) {
    if (!skillNames || skillNames.length === 0) continue;
    const result = generateCategoryFile(catName, skillNames, allSkills, commandsDir);
    results.push({ category: catName, ...result });
  }

  return results;
}

function deleteCategoryFile(categoryName, commandsDir) {
  const filePath = path.join(commandsDir, `st-${categoryName}.md`);
  try { fs.unlinkSync(filePath); } catch {}
}

module.exports = { generateCategoryFile, generateAllCategoryFiles, deleteCategoryFile };
